version: 2.1
orbs:
  node: circleci/node@4.1.0
  eb: circleci/aws-elastic-beanstalk@2.0.0
  aws-cli: circleci/aws-cli@2.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup:
          profile-name: AWS_PROFILE
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_DEFAULT_REGION
      - eb/setup
      - run:
          name: Front-End Install
          command: npm run frontend:install
      - run:
          name: Back-End Install
          command: npm run backend:install
      - run:
          name: Front-End Build
          command: npm run frontend:build
      - run:
          name: Back-End Build
          command: npm run backend:build
      - run:
          name: Deploy Back-End
          command: |
            npm run backend:deploy
      - run:
          name: Deploy Front-End
          command: |
            aws s3 cp --recursive --acl public-read ./www s3://udagram-frontend-angular-4/
